server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_room?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.studyroom.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  secret: your-secret-key
  expiration: 86400000  # 24小时

# 跨域配置
cors:
  allowed-origins: "*"  # 允许所有来源
  allowed-methods: "*"  # 允许所有方法
  allowed-headers: "*"  # 允许所有头信息
  allow-credentials: true
  max-age: 3600

# 日志配置
logging:
  level:
    root: INFO
    com.studyroom: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG 